spring:
  application:
    name: store
  datasource:
    url: jdbc:postgresql://localhost:5432/store
    username: storedev
    password: storedev
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
server:
  port: 8443
  ssl:
    enabled: true
    certificate: classpath:localhost.pem
    certificate-private-key: classpath:localhost-key.pem
logging:
  level:
    org.hibernate.tool.hbm2ddl: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure: INFO

storage:
  s3:
    endpoint: http://localhost:9000
    accessKey: minioadmin
    secretKey: minioadmin123
    bucket: images
    region: us-east-1
    publicBaseUrl: http://localhost:9000/images